
CREATE TABLE CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR (
    COD_COLABORADOR 			NUMBER(19) GENERATED ALWAYS AS IDENTITY,  
    COD_CAMPANIA 		        NUMBER(19),
    COD_EJECUTIVO 		        VARCHAR2(4),
    NOM_COLABORADOR 		    VARCHAR2(255),
    TIP_DOCUMENTO 		        VARCHAR2(255),
    NUM_DOCUMENTO 			    VARCHAR2(255),
    DES_EMAIL 				    VARCHAR2(255),
    COD_TELEFONO 			    VARCHAR2(255),
    NUM_TELEFONO 			    VARCHAR2(255),
    FEC_CREACION                TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
tablespace CACTUS_SAFI
pctfree 10
initrans 1
maxtrans 255
storage
(
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
);

COMMENT ON TABLE CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR IS 'Tabla para almacenar campañas';
COMMENT ON COLUMN CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR.COD_COLABORADOR IS 'Codigo unico';
COMMENT ON COLUMN CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR.COD_CAMPANIA IS 'Codigo de campaña';
COMMENT ON COLUMN CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR.COD_EJECUTIVO IS 'Codigo unico';
COMMENT ON COLUMN CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR.NOM_COLABORADOR IS 'Nombre de colaborador';
COMMENT ON COLUMN CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR.TIP_DOCUMENTO IS 'Tipo de documento';
COMMENT ON COLUMN CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR.NUM_DOCUMENTO IS 'Numero de documento';
COMMENT ON COLUMN CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR.DES_EMAIL IS 'Descripcion de email';
COMMENT ON COLUMN CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR.COD_TELEFONO IS 'Codigo de pais del telefono';
COMMENT ON COLUMN CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR.NUM_TELEFONO IS 'Numero de telefono';
COMMENT ON COLUMN CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR.FEC_CREACION IS 'Fecha de creación del registro';

-- Create/Recreate primary, unique and foreign key constraints 
alter table CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR
add constraint SWB_CAMPANIA_COLABORADOR_PK primary key (COD_COLABORADOR)
using index 
tablespace CACTUS_SAFI
pctfree 10
initrans 2
maxtrans 255
storage
(
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
); 

-- Grant/Revoke object privileges 
grant select, insert, update, delete on CACTUS_SAFI.SWB_CAMPANIA_COLABORADOR to WEBUSER;

